# Generated by Django 5.1.4 on 2025-01-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
    ]
