# Generated by Django 5.1.4 on 2025-01-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
